# Generated by Django 6.0.6 on 2026-06-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='cart',
            new_name='wishlist',
        ),
    ]
